name: Integration django

on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  integration-django:
    uses: ./.github/workflows/integration-reusable.yml
    with:
      integration: django
    secrets: inherit
