name: Integration fastapi

on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  integration-fastapi:
    uses: ./.github/workflows/integration-reusable.yml
    with:
      integration: fastapi
    secrets: inherit
