name: Integration aiohttp

on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  integration-aiohttp:
    uses: ./.github/workflows/integration-reusable.yml
    with:
      integration: aiohttp
    secrets: inherit
