name: Integration flask

on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  integration-flask:
    uses: ./.github/workflows/integration-reusable.yml
    with:
      integration: flask
    secrets: inherit
