name: Integration requests

on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  integration-requests:
    uses: ./.github/workflows/integration-reusable.yml
    with:
      integration: requests
    secrets: inherit
