name: Integration starlette

on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  integration-starlette:
    uses: ./.github/workflows/integration-reusable.yml
    with:
      integration: starlette
    secrets: inherit
