name: Integration falcon

on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  integration-falcon:
    uses: ./.github/workflows/integration-reusable.yml
    with:
      integration: falcon
    secrets: inherit
